[package]
name = "clog_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = {version = "2.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.20"

[lib]
proc-macro = true
