[package]
name = "clog_ws_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "*", features = ["derive"]}
postcard = { version = "*", features = ["use-std"] }
bytes = "*"
clog_core = { path = "../core" }
